# Generated by Django 3.2.6 on 2021-08-27 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='user_profile_info', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctornotification',
            name='doctor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='doctor_profile_info', to=settings.AUTH_USER_MODEL),
        ),
    ]
