# Generated by Django 3.2.6 on 2021-12-17 12:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='booking_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='booking_status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('not_confirmed', 'Not_Confirmed')], default='not_confirmed', max_length=20),
        ),
    ]
