# Generated by Django 3.2.6 on 2021-12-29 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_appointments_is_active'),
        ('appointment', '0003_auto_20211217_1229'),
    ]

    operations = [
    ]
