# Generated by Django 3.2.6 on 2021-08-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthtest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='question_type',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
