# Generated by Django 3.2.6 on 2021-08-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthtest', '0002_questions_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usermentalhealth',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
