# Generated by Django 3.2.3 on 2021-10-24 15:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('healthtest', '0003_auto_20210827_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionList',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('no_of_question', models.BigIntegerField(default=0, null=True)),
                ('test_type', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('disease_type', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='usermentalhealth',
            name='tests',
            field=models.JSONField(default={}),
        ),
    ]
