# Generated by Django 3.2.3 on 2021-10-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthtest', '0004_auto_20211024_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermentalhealth',
            name='tests',
            field=models.JSONField(),
        ),
    ]
