# Generated by Django 3.2.3 on 2021-10-25 12:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthtest', '0009_alter_usermentalhealth_tests'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionlist',
            name='questions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(blank=True), default=None, null=True, size=None),
        ),
        migrations.AddField(
            model_name='usermentalhealth',
            name='doctors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(blank=True), default=None, null=True, size=None),
        ),
    ]
