# Generated by Django 3.2.3 on 2021-10-25 12:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermgmt', '0002_auto_20211024_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='working_hours',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=None, null=True, size=None),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), default=None, help_text='Language codes of preferred languages in the order of preference', null=True, size=None),
        ),
        migrations.AddField(
            model_name='user',
            name='timezones',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=None, null=True, size=None),
        ),
    ]
