# Generated by Django 3.2.3 on 2021-10-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermgmt', '0003_auto_20211025_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo_url',
            field=models.URLField(default='https://unsplash.com/photos/s5kTY-Ve1c0', help_text='An optional image of the user', null=True),
        ),
    ]
